.PHONY: test
test:
	# k6 run --vus 10 --duration 30s tests/script.js
	# k6 run --vus 10 --duration 5s tests/script.js
	# sleep 5
	# k6 run --vus 100 --duration 5s tests/script.js
	# k6 run --vus 100 --duration 30s tests/script.js
	# sleep 5
	k6 run --vus 500 --duration 5s tests/script.js
	# sleep 5
	# k6 run --vus 1000 --duration 5s tests/script.js
	# sleep 5
	# k6 run --vus 2000 --duration 5s tests/script.js
